In [21]:
# 姓名：杜斌 暗号： 无

In [58]:
# 1. 从列表创建Series

import numpy as np
import pandas as pd
from pandas import Series,DataFrame

sel = Series([1,2,3,4], index = ['a','b','c','d'])
print(sel)

a    1
b    2
c    3
d    4
dtype: int64


In [59]:
# 2. 从Numpy数组创建DataFrame

df = DataFrame(np.random.randint(0,10,(4,4)), index = [1,2,3,4], columns=['a','b','c','d'])
print(df)

   a  b  c  d
1  3  8  4  6
2  0  8  4  9
3  7  1  5  8
4  4  0  9  7


In [60]:
# 3. 显示df的基础信息，包括⾏的数量；列名；每⼀列值的数量、类型
# 显示df的基础信息
print(df.info())

# 获取行的数量
print("*"*30)
print(df.shape[0])

# 获取列名
print("*"*30)
print(df.columns.tolist())

# 获取每一列的数量
print("*"*30)
print(df[:].count())

# 获取每一列的值
print("*"*30)
print(df.iloc[:].values)

# 获取每一列值的类型
print("*"*30)
print(df.dtypes)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 1 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       4 non-null      int64
 1   b       4 non-null      int64
 2   c       4 non-null      int64
 3   d       4 non-null      int64
dtypes: int64(4)
memory usage: 160.0 bytes
None
******************************
4
******************************
['a', 'b', 'c', 'd']
******************************
a    4
b    4
c    4
d    4
dtype: int64
******************************
[[3 8 4 6]
 [0 8 4 9]
 [7 1 5 8]
 [4 0 9 7]]
******************************
a    int64
b    int64
c    int64
d    int64
dtype: object


In [61]:
# 4. 展示df的前3行
print(df.head(3))

   a  b  c  d
1  3  8  4  6
2  0  8  4  9
3  7  1  5  8


In [62]:
# 5. 设置x,y轴标签variable x，value y
## 设定x轴variable x
df.index = ['a','b','c','d']

## 设定y轴value y
df.columns = ['1','2','3','4']

print(df)

   1  2  3  4
a  3  8  4  6
b  0  8  4  9
c  7  1  5  8
d  4  0  9  7


In [63]:
str = 'Python'
print(f'Hello {str}')

Hello Python
