# classic machine learning 1

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
filename = '../resource/dataset.txt'

In [3]:
data = open(filename)

for line in data.readlines():
    print(line)
    print(f'line.strip(): {line.strip()}')
    print(f'line.split(): {line.split()}')
    print(f'line.strip().split(): {line.strip().split()}')

    break

-0.017612	14.053064	0

line.strip(): -0.017612	14.053064	0
line.split(): ['-0.017612', '14.053064', '0']
line.strip().split(): ['-0.017612', '14.053064', '0']


In [6]:
def loadDataset(filename):
    data_list = []
    label_list = []

    data = open(filename)
    for line in data.readlines():
        line_arr = line.strip().split()
        data_list.append([1.0, float(line_arr[0]), float(line_arr[1])])
        label_list.append(int(line_arr[2]))
    return data_list, label_list

In [7]:
data_list, label_list = loadDataset(filename)
print(data_list[0])
print(label_list[0])

[1.0, -0.017612, 14.053064]
0


In [8]:
# sigmoid func
def sigmoid(x):
    x_max = x.max()
    return np.exp(x-x_max)/(np.exp(-x_max) + np.exp(x - x_max))
    # return 1.0 / 1.0 + np.exp(-x)

In [9]:
data_arr = np.array(data_list)
label_arr = np.array(label_list)

print('data_arr.shape: ', data_arr.shape)
print('label_arr.shape: ', label_arr.shape)

data_arr.shape:  (100, 3)
label_arr.shape:  (100,)


In [13]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

print(a * b)

print(a.dot(b))

# 19 = 1* 5 + 2*7
# 22 = 1*6 + 2*8
# 43 = 3*5 + 4*7 
# 50 = 3*7 + 4*8

print(np.dot(a,b))
print(a @ b)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [16]:
a = np.array([[1], [2], [3]])
b = np.array([4,5,6])

print(a.shape)
print(b.shape)

c = a-b
print(c)
print(c.shape)

d = np.array([[4,5,6], [4,5,6], [4,5,6]])

e = np.array([[1,1,1],[2,2,2], [3,3,3]])

print(d - e)

(3, 1)
(3,)
[[-3 -4 -5]
 [-2 -3 -4]
 [-1 -2 -3]]
(3, 3)
[[3 4 5]
 [2 3 4]
 [1 2 3]]


In [17]:
def gradAscent(data_list, label_list):
    data_arr = np.array(data_list)
    label_arr = np.array(label_list).reshape(-1, 1)
    # label_array = np.array(label_list).transpose()
    # label_array = np.array(label_list)
    m, n = np.shape(data_arr)
    alpha = 0.1
    max_cycles = 500
    weights = np.ones((n, 1))

    for k in range(max_cycles):
        predict = sigmoid(data_arr @ weights)
        # print('predict: ', predict.shape)
        error = label_arr - predict
        weights = weights + alpha * (data_arr.transpose() @ error)
    return weights # (3, 1)

In [18]:
from numpy import *
def plotBestFit(weights, dataMat, labelMat):
    dataArr = np.array(dataMat)
    n = np.shape(dataArr)[0]
    xcord1 = []; ycord1 = []
    xcord2 = []; ycord2 = []
    for i in range(n):
        if int(labelMat[i]) == 1:
            xcord1.append(dataArr[i, 1])
            ycord1.append(dataArr[i, 2])
        else:
            xcord2.append(dataArr[i, 1])
            ycord2.append(dataArr[i, 2])
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.scatter(xcord1, ycord1, s = 30, c = 'red', marker = 's')
    ax.scatter(xcord2, ycord2, s = 30, c = 'green')
    x = np.arange(-3.0, 3.0, 0.1)
    y = (-weights[0] - weights[1] * x) / weights[2]
    ax.plot(x, y)
    plt.xlabel('X1')
    plt.ylabel('X2')
    plt.show()

In [ ]:
def main():
    data_list, label_list = loadDataset(filename)
    weights = gradAscent(data_list, label_list)
    plotBestFit(weights, data_list, label_list)