In [1]:
# Coding K-Means by self




In [1]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn import datasets, preprocessing
import random, sys

In [20]:
# load data
iris_set = datasets.load_iris()
iris_data = iris_set.data
iris_target = iris_set.target

print('iris_data=>'+str(iris_data))
print('iris_target=>'+str(iris_target))

min_max_scaler = preprocessing.MinMaxScaler()
iris_set_normal = min_max_scaler.fit_transform(iris_data)
print('iris_normal=>'+str(iris_set_normal))

iris_data=>[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 

In [21]:
# KMeans by Self
def my_kmeans(train_data, k, train_target):
    r_n = len(train_data)
    f_n = len(train_data[0])
    n_k_min = r_n / k / 4 # 类别内个数少于此时，重新随机

    core_list = [[random.random() for j in range(f_n)] for i in range(k)]
    print('core_list=>'+str(core_list))
    for eps in range(20): # 迭代次数
        row_core=[] # 当前行的最近类（中心）
        for i in range(r_n): # 遍历数据记录
            core_dist=[] # 当前行，每个
            for j in range(k): # 遍历每个类中心
                t_dist = 0.0
                for m in range(f_n): # 遍历每个特征
                    t_dist=t_dist+ abs(core_list[j][m] - train_data[i][m])
                core_dist.append(t_dist) # 当前类别的距离
            i_k = np.argmin(core_dist) # 最近的类别序号
            row_core.append(i_k) # 当前行的类别

        core_f_sum = [[0 for j in range(f_n)] for i in range(k)] # 各分类各指标
        core_row_cnt = [0 for i in range(k)]  # 各分类的个数
        for i in range(r_n):  # 遍历数据记录
            core_idx = row_core[i]
            core_row_cnt[core_idx] =+1
            for m in range(f_n): # 遍历每个特征,做同类的累加
                core_f_sum[core_idx][m] =+ train_data[i][m]


        # 更新类别中心位置
        for j in range(k): # 遍历每个类中心
            n_k = core_row_cnt[j]
            if n_k>n_k_min:
                for m in range(f_n): # 遍历每个特征,求均值
                    core_list[j][m] = core_f_sum[j][m] / n_k
            else:
                # 类内个数小于阈值则重新随机
                core_list[j] = [random.random() for f in range(f_n)]

        for i in range(r_n):  # 遍历数据记录
            print(str(eps*10000+i)+'=>'+str(train_data[i])+' -> '+str(row_core[i])+' <- '+str(train_target[i]))

    return train_data, row_core, core_list #返回各类的中心位置

In [22]:
# Use KMeans by Self
_, y_pred_1, _ = my_kmeans(iris_set_normal, 3, iris_target)

core_list=>[[0.5803725653567378, 0.9502826527788514, 0.13425655154549299, 0.4873051426122441], [0.06497709027788579, 0.5226171280313868, 0.32213410035343926, 0.5581846744419496], [0.09649801583653228, 0.8226171734501315, 0.5799261069014792, 0.48608544999751824]]
0=>[0.22222222 0.625      0.06779661 0.04166667] -> 1 <- 0
1=>[0.16666667 0.41666667 0.06779661 0.04166667] -> 1 <- 0
2=>[0.11111111 0.5        0.05084746 0.04166667] -> 1 <- 0
3=>[0.08333333 0.45833333 0.08474576 0.04166667] -> 1 <- 0
4=>[0.19444444 0.66666667 0.06779661 0.04166667] -> 1 <- 0
5=>[0.30555556 0.79166667 0.11864407 0.125     ] -> 0 <- 0
6=>[0.08333333 0.58333333 0.06779661 0.08333333] -> 1 <- 0
7=>[0.19444444 0.58333333 0.08474576 0.04166667] -> 1 <- 0
8=>[0.02777778 0.375      0.06779661 0.04166667] -> 1 <- 0
9=>[0.16666667 0.45833333 0.08474576 0.        ] -> 1 <- 0
10=>[0.30555556 0.70833333 0.08474576 0.04166667] -> 0 <- 0
11=>[0.13888889 0.58333333 0.10169492 0.04166667] -> 1 <- 0
12=>[0.13888889 0.41666667 

In [23]:
# KMeans by Sklearn
def sklearn_kmeans(train_data, k, train_target):
    r_n = len(train_data)
    model = KMeans(k, init='random')

    result = model.fit(train_data)
    labels = result.labels_


    for i in range(r_n):  # 遍历数据记录
        print(str(210000 + i) + '=>' + str(train_data[i]) + ' -> ' + str(labels[i]) + ' <- ' + str(train_target[i]))

    return train_data, labels

In [24]:
# Use K-Means by Sklearn
_, y_pred_2= sklearn_kmeans(iris_set_normal, 3, iris_target)

210000=>[0.22222222 0.625      0.06779661 0.04166667] -> 0 <- 0
210001=>[0.16666667 0.41666667 0.06779661 0.04166667] -> 0 <- 0
210002=>[0.11111111 0.5        0.05084746 0.04166667] -> 0 <- 0
210003=>[0.08333333 0.45833333 0.08474576 0.04166667] -> 0 <- 0
210004=>[0.19444444 0.66666667 0.06779661 0.04166667] -> 0 <- 0
210005=>[0.30555556 0.79166667 0.11864407 0.125     ] -> 0 <- 0
210006=>[0.08333333 0.58333333 0.06779661 0.08333333] -> 0 <- 0
210007=>[0.19444444 0.58333333 0.08474576 0.04166667] -> 0 <- 0
210008=>[0.02777778 0.375      0.06779661 0.04166667] -> 0 <- 0
210009=>[0.16666667 0.45833333 0.08474576 0.        ] -> 0 <- 0
210010=>[0.30555556 0.70833333 0.08474576 0.04166667] -> 0 <- 0
210011=>[0.13888889 0.58333333 0.10169492 0.04166667] -> 0 <- 0
210012=>[0.13888889 0.41666667 0.06779661 0.        ] -> 0 <- 0
210013=>[0.         0.41666667 0.01694915 0.        ] -> 0 <- 0
210014=>[0.41666667 0.83333333 0.03389831 0.04166667] -> 0 <- 0
210015=>[0.38888889 1.         0.0847457

In [25]:
# The accuracy of K-Means by Self
(y_pred_1 == iris_target).sum() / len(iris_target)

0.6733333333333333

In [26]:
# The accuracy of K-Means by Sklearn
(y_pred_2 == iris_target).sum() / len(iris_target)

0.8866666666666667