In [1]:
# 1. ndarray与Python原生list运算效率对比
# import random
# import time
# import numpy as np
# a = []
# for i in range(100000000):
#     a.append(random.random())
# t1 = time.time()
# sum1 = sum(a)
# t2 = time.time()
# b = np.array(a)
# t4 = time.time()
# sum3 = np.sum(b)
# t5 = time.time()
# print(t2-t1,t5-t4)

1.0616569519042969 0.08224916458129883


In [1]:
# NumPy的Ndarray对象
# 2. 创建一维数组
import random
import time
import numpy as np
list1 = [1,2,3,4]
# oneArray = np.array(list1)
# print(type(oneArray))
# print(oneArray)

# 创建数组的多种形式
# 直接传入列表的方式
# t1 = np.array([1,2,3])
# print(type(t1))
# print([t1])
# # 传入range生成序列
# t2 = np.array(range(10))
# print(type(t2))
# print(t2)
# # 使用numpy自带的np.arange()生成数组
t3 = np.arange(0,10,2)
print(type(t3))
print(t3)

<class 'numpy.ndarray'>
[0 2 4 6 8]


In [2]:
# 3. 创建二维数组
list2 = [[1,2],[3,4],[5,6],[7,8]]
twoArray = np.array(list2)
print(twoArray)
print('a')

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
a


In [6]:
# 4. 常用属性
list2 = [[1,2],[3,4],[5,6]]
twoArray = np.array(list2)
# 获取数组的维度
print(twoArray.ndim)
# 形状
print(twoArray.shape)
# 有多少个元素
print(twoArray.size)

2
(3, 2)
6


In [ ]:
# # 5. 调整数组的形状
# four = np.array([[1,2,3],[4,5,6]])
# print(four)

# # 修改的是原有的
# four.shape = (3,2)
# print('*'*30)
# print(four)


# # 返回一个新的数组
four_other = np.array([[1,2,3],[4,5,6]])
four_other_new = four_other.reshape(3,2)
# print('*'*30))
# print(four_other)
# print('*'*30)
print(four_other_new)

# # 将多维变成一维数组
five = four.reshape((6),order='C') # 'C'和'F'的展开方式不一样
print('*'*30)
print(five)

# 转成二维数组
t = np.arange(24)
t1 = t.reshape(4,6)
print(t1)

# 转成三维数组
t2 = t.reshape(2,3,4)
print(t2)

In [7]:
# 6. 转化成list
a = np.array([9,12,88,14,25])
print(type(a))
list_a = a.tolist()
print(list_a)
print(type(list_a))

<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


In [8]:
# 7. 数据类型
f = np.array([1,2,3,4,5], dtype = np.int16)
print(f.itemsize)
print(f.dtype)
f1 = f.astype(np.float)
print(f1.dtype)

2
int16
float64


In [11]:
# 8. 一维数组的切片
a = np.arange(10)
print(a)

# 冒号分隔切片参数 start:stop:step来进行切片操作
print(a[2:7:2]) # 从索引2开始到索引7停止，间隔为2

# 如果只放置一个参数，如[2], 将返回与该索引想对应的单个元素
print(a[2],a)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
2 [0 1 2 3 4 5 6 7 8 9]


In [23]:
# 9. 多位数组的切片
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)

# t1[行,列]
# print(t1[1]) # 取一行
# print(t1[1,:]) # 取一行
# print(t1[1:]) # 取连续多行
# print('#'*20) # 取连续多行
# print(t1[1:3,:])
# print('#'*20)
# print(f'不连续的多行: \n{t1[[0,2,3]]}') # 取不连续的多行
# print(t1[[0,2,3],:])
print(t1[:,1]) # 取一列
# print('#'*20)
# print(t1[:,1:]) # 取连续多列
# print(t1[:,[0,2,3]])
# print(t1[2,3]) # 取某一个值
# print(t1[[0,1,1],[0,1,3]])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]


In [ ]:
# 10. 根据条件取值
# t = np.arange(24).reshape(4,6)
# print(t)
# print('*'*20)
# t[t<10] = 0
# print(t)
# t[(t>2)&(t<6)] = 0
# t[(t<2)|(t>6)] = 1
# t[~(t>6)]=0
# t
## 拓展
## 三目运算 np.where(condition,x,y)
score= np.array([[80,88],[82,81],[75,81]])
print(score)
result = np.where(score>80,1,0)
print(result)

In [ ]:
## 11. 轴
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a,axis=0))