In [1]:
# 1. ndarray与Python原生list运算效率对比
# import random
# import time
# import numpy as np
# a = []
# for i in range(100000000):
#     a.append(random.random())
# t1 = time.time()
# sum1 = sum(a)
# t2 = time.time()
# b = np.array(a)
# t4 = time.time()
# sum3 = np.sum(b)
# t5 = time.time()
# print(t2-t1,t5-t4)

1.0616569519042969 0.08224916458129883


In [1]:
# NumPy的Ndarray对象
# 2. 创建一维数组
import random
import time
import numpy as np
list1 = [1,2,3,4]
# oneArray = np.array(list1)
# print(type(oneArray))
# print(oneArray)

# 创建数组的多种形式
# 直接传入列表的方式
# t1 = np.array([1,2,3])
# print(type(t1))
# print([t1])
# # 传入range生成序列
# t2 = np.array(range(10))
# print(type(t2))
# print(t2)
# # 使用numpy自带的np.arange()生成数组
t3 = np.arange(0,10,2)
print(type(t3))
print(t3)

<class 'numpy.ndarray'>
[0 2 4 6 8]


In [2]:
# 3. 创建二维数组
list2 = [[1,2],[3,4],[5,6],[7,8]]
twoArray = np.array(list2)
print(twoArray)
print('a')

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
a


In [6]:
# 4. 常用属性
list2 = [[1,2],[3,4],[5,6]]
twoArray = np.array(list2)
# 获取数组的维度
print(twoArray.ndim)
# 形状
print(twoArray.shape)
# 有多少个元素
print(twoArray.size)

2
(3, 2)
6


In [ ]:
# # 5. 调整数组的形状
# four = np.array([[1,2,3],[4,5,6]])
# print(four)

# # 修改的是原有的
# four.shape = (3,2)
# print('*'*30)
# print(four)


# # 返回一个新的数组
four_other = np.array([[1,2,3],[4,5,6]])
four_other_new = four_other.reshape(3,2)
# print('*'*30))
# print(four_other)
# print('*'*30)
print(four_other_new)

# # 将多维变成一维数组
five = four.reshape((6),order='C') # 'C'和'F'的展开方式不一样
print('*'*30)
print(five)

# 转成二维数组
t = np.arange(24)
t1 = t.reshape(4,6)
print(t1)

# 转成三维数组
t2 = t.reshape(2,3,4)
print(t2)

In [7]:
# 6. 转化成list
a = np.array([9,12,88,14,25])
print(type(a))
list_a = a.tolist()
print(list_a)
print(type(list_a))

<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


In [8]:
# 7. 数据类型
f = np.array([1,2,3,4,5], dtype = np.int16)
print(f.itemsize)
print(f.dtype)
f1 = f.astype(np.float)
print(f1.dtype)

2
int16
float64


In [11]:
# 8. 一维数组的切片
a = np.arange(10)
print(a)

# 冒号分隔切片参数 start:stop:step来进行切片操作
print(a[2:7:2]) # 从索引2开始到索引7停止，间隔为2

# 如果只放置一个参数，如[2], 将返回与该索引想对应的单个元素
print(a[2],a)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
2 [0 1 2 3 4 5 6 7 8 9]


In [23]:
# 9. 多位数组的切片
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)

# t1[行,列]
# print(t1[1]) # 取一行
# print(t1[1,:]) # 取一行
# print(t1[1:]) # 取连续多行
# print('#'*20) # 取连续多行
# print(t1[1:3,:])
# print('#'*20)
# print(f'不连续的多行: \n{t1[[0,2,3]]}') # 取不连续的多行
# print(t1[[0,2,3],:])
print(t1[:,1]) # 取一列
# print('#'*20)
# print(t1[:,1:]) # 取连续多列
# print(t1[:,[0,2,3]])
# print(t1[2,3]) # 取某一个值
# print(t1[[0,1,1],[0,1,3]])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]


In [32]:
# 10. 根据条件取值
t = np.arange(24).reshape(4,6)
print(t)
print('*'*20)
# t<10
'''
[[ True,  True,  True,  True,  True,  True],
[ True,  True,  True,  True, False, False],
[False, False, False, False, False, False],
[False, False, False, False, False, False]]
'''
# python中的与或非"and or not"不能用于NumPy中

# t[t<10] = 0
# print(t)
# t[(t>2)&(t<6)] = 0 # 与 &
# t[(t<2)|(t>6)] = 1 # 或 |
# t[~(t>6)]=0 # 非 ~
# t
## 拓展
## 三目运算 np.where(condition,x,y)
# score= np.array([[80,88],[82,81],[75,81]])
# print(score)
result = np.where(score>80,1,0)
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[0 1]
 [1 1]
 [0 1]]


In [46]:
# 11. 轴
# a = np.array([[1,2,3],[4,5,6]])
# print(a)
# print("*"*30)
# print(np.sum(a,axis=1))
# print("*"*30)
# print(np.sum(a,axis=0))

# 三维
a = np.arange(27).reshape((3,3,3))
print(a)
print("*"*30)
# print(np.sum(a,axis=0))
# print(np.sum(a,axis=1))
print(np.sum(a,axis=2))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
******************************
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


In [58]:
# 12 。 数组和数的计算
t1 = np.arange(24).reshape((6,4))
print(t1)
print('*'*30)
# print(t1+2)
# print(t1*2)
print(t1/2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
******************************
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [70]:
# 13. 数组和数组之间的操作
# 1). 同种形状的多数数组计算
# t1 = np.arange(24).reshape((6,4))
# t2 = np.arange(100,124).reshape((6,4))
# print(f'{t1}\n{t2}')
# print("*"*30)
# print(t1+t2)
# print(t1*t2)

# 2). 不同形状的多维数组不能计算
# t1 = np.arange(24).reshape((4,6)) 
# t2 = np.arange(18).reshape((3,6)) 
# print(t1) 
# print(t2) 
# print(t1-t2)

# 3）. 行数或者列相同的一维数组和多位数组可以进行计算：
# 行相同
# t1 = np.arange(24).reshape((4,6))
# t2 = np.arange(0,6)
# print(t1)
# print(t2)
# print(t1-t2)

# 列相同
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1)
print(t2)
print(t1-t2)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


In [129]:
# 14. NumPy的计算方法
import numpy as np
score = np.array([[80,88],[82,81],[75,81]])
# # 1). 获取所有数据最大值
# result = np.max(score)

# # 2). 获取某一个轴上的数据最大值
# result = np.max(score,axis=0)

# # 3). 获取最小值
# result = np.min(score)

# # 4). 获取某一个轴上的数据最小值
# result = np.min(score,axis=0)

# # 5). 数据的比较
# result = np.maximum([-2,-1,0,1,2],0) # 第一个参数中的每一个数与第二个比较

# result = np.minimum([-2,-1,0,1,2],0)

# # 6). 求平均值
# result = np.mean(score) # 获取所有数据的平均值
# result = np.mean(score, axis=0) # 获取某一行或者某一列的平均值

# print(result)

# 7). 返回给定axis上的累计和
arr = np.array([[1,2,3],[4,5,6]])
# print(arr)
# print(arr.cumsum(0))
# print(arr.cumsum(1))

# 8). argmin球最小值索引
result = np.argmin(score,axis=0)
print(result)

[2 1]


In [93]:
# 16. 数组的nan
# 创建一个nan
# a = np.nan
# print(a,type(a)) # nan <class 'float'>
# print(np.isnan(a))

# 判断数组中的nan的个数
t = np.arange(24,dtype=float).reshape(4,6)
print(t)
t[3,4] = np.nan
print("*"*30)
print(t)

# 注意： nan和任何数计算都为nan
# print(np.sum(t,axis=0))
'''
[36. 40. 44. 48. nan 56.]
'''

# 判断nan
# np.isnan(t)

# 替换nan
# t[np.isnan(t)] = 0
# t
print(np.sum(t,axis=0))

# 获取数组中nan的个数
# print(np.nan == np.nan) # nan不等于nan, False

# t != t # 可以获取到True的nan值
# 可以使用np.count_nonzero() 来判断非0的个数
# print(np.count_nonzero(t))
# 所以我们可以使用这两个结合使用判断nan的个数
print(np.count_nonzero(t != t))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
******************************
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]
[36. 40. 44. 48. nan 56.]
1


In [110]:
# 练习
t = np.arange(24).reshape(4,6).astype('float')
# 将数组中的一部分替换nan
t[1,3:] = np.nan
print(t)

'''
要求，nan用一列的平均值去填充
'''

# 首先，遍历每一列，判断是否有nan
for i in range(t.shape[1]):
    # 获取当前列数据
    temp_col = t[:,i]
    print(temp_col)
    # 判断当前列的数据是否含有nan
    nan_num = np.count_nonzero(temp_col != temp_col)
    print(nan_num)
    if nan_num != 0: # 如果成立则说明含有nan
        # 将这一列不为nan的数据拿出来
        temp_col_nNan = temp_col[temp_col == temp_col]
        print("*"*30)
        print('不为nan的数据:',temp_col_nNan)
        # 将nan替换成这一列的平均值
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_nNan)
print(t)
        

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[ 0.  6. 12. 18.]
0
[ 1.  7. 13. 19.]
0
[ 2.  8. 14. 20.]
0
[ 3. nan 15. 21.]
1
******************************
不为nan的数据: [ 3. 15. 21.]
[ 4. nan 16. 22.]
1
******************************
不为nan的数据: [ 4. 16. 22.]
[ 5. nan 17. 23.]
1
******************************
不为nan的数据: [ 5. 17. 23.]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
