# 练习1

## 1+3+5+..+99的求和

In [1]:
### 解法1
num = 0
for i in range(1, 100, 2):
    num = num + i
print(num)

### 解法2
print(sum(range(1, 100, 2)))

2500
2500


## 创建数组

In [8]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b[1,1] = 10
print(a.shape)
print(b.shape)
print(a.dtype)
print(b)

(3,)
(3, 3)
int64
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


## 结构数组

In [1]:
# -*- coding: utf-8 -*-  
import numpy as np
import string 
persontype = np.dtype({'names':['name','age','chinese','math','english'], 'formats':['S32','i','i','i','f']})
# peoples = np.array([(u"张飞",23,86,16,67),(u"关羽",28,67,92,56),(u"赵云",21,82,97,89),(u"黄忠",56,97,62,34)], dtype=persontype)
peoples = np.array([("ZhangFei",32,75,100, 90),("GuanYu",24,85,96,88.5),("ZhaoYun",28,85,92,96.5),("HuangZhong",29,65,85,100)],dtype=persontype)
ages = peoples[:]['age']
chineses = peoples[:]['chinese']
maths = peoples[:]['math']
englishs = peoples[:]['english']
print('age mean:',np.mean(ages))
print('chinese mean:',np.mean(chineses))
print('math mean:',np.mean(maths))
print('english mean:',np.mean(englishs))

age mean: 28.25
chinese mean: 77.5
math mean: 93.25
english mean: 93.75


In [30]:
# ufunc运算

In [25]:
## 连续数组的创建
x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)
print(x1)
print(x2)

[1 3 5 7 9]
[1. 3. 5. 7. 9.]


In [32]:
## 算数运算
x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)
print(np.add(x1, x2)) 
print(np.subtract(x1, x2))
print(np.multiply(x1, x2))
print(np.divide(x1, x2))
print(np.power(x1, x2))
print(np.remainder(x1, x2))

[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.]
[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]
[0. 0. 0. 0. 0.]


In [37]:
# 统计函数
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [38]:
# 计数组 / 矩阵中的最大值函数 amax()，最小值函数 amin()
print(np.amin(a))
print(np.amin(a,0))
print(np.amin(a,1))
print(np.amax(a))
print(np.amax(a,0))
print(np.amax(a,1))

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


In [40]:
# 统计最大值与最小值之差 ptp()
print(np.ptp(a))
print(np.ptp(a,0))
print(np.ptp(a,1))

8
[6 6 6]
[2 2 2]


In [41]:
# 统计数组的百分位数 percentile()
print(np.percentile(a,50))
print(np.percentile(a,50,0))
print(np.percentile(a,50,1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [42]:
# 统计数组中的中位数 median()、平均数 mean()
## 中位数
print(np.median(a))
print(np.median(a,0))
print(np.median(a,1))

## 平均数
print(np.mean(a))
print(np.mean(a,0))
print(np.mean(a,1))

5.0
[4. 5. 6.]
[2. 5. 8.]
5.0
[4. 5. 6.]
[2. 5. 8.]


In [43]:
# 统计数组中的加权平均值 average()
a = np.array([1,2,3,4])
wts = np.array([1,2,3,4])
print(np.average(a))
print(np.average(a,weights = wts))
print((1*1+2*2+3*3+4*4)/(1+2+3+4))

2.5
3.0
3.0


In [44]:
# 统计数组中的标准差 std()、方差 var()
a = np.array([1,2,3,4])
print(np.std(a))
print(np.var(a))

1.118033988749895
1.25


In [49]:
# Numpy 排序
a = np.array([[4,3,2],[2,4,1]])
print(np.sort(a))
print(np.sort(a, axis=None,kind='quicksort'))
print(np.sort(a,0,kind='mergesort'))
print(np.sort(a,1,kind='heapsort'))


[[2 3 4]
 [1 2 4]]
[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
[[2 3 4]
 [1 2 4]]


In [65]:
# 练习：班级成绩排名
import numpy as np
persontype = np.dtype({'names':['name','chinese','english','math'],'formats':['S32','i','i','i']})
persons = np.array([('zhangfei',66,65,30),('guanyu',95,85,98),('zhaoyun',93,92,96),('huangzhong',90,88,77),('dianwei',80,90,90)],dtype=persontype)

# 指定竖排
names = persons[:]['name']
chineses = persons[:]['chinese']
englishs = persons[:]['english']
maths = persons[:]['math']

# 定义函数用于显示每一排
def show(names,num):
    print(f'|{names}|{np.mean(num)}|{np.amin(num)}|{np.amax(num)}|{np.var(num)}|{np.std(num)}|')
    
print('|科目|平均成绩|最小成绩|最大成绩|方差|标准差|')
show('语文',chineses)
show('英语',englishs)
show('数学',maths)

# print(np.mean(chineses))
# print(np.mean(englishs))
# print(np.mean(maths))
# print(np.amax(chineses))
# print(np.amax(englishs))
# print(np.amax(maths))
# print(np.amin(chineses))
# print(np.amin(englishs))
# print(np.amin(maths))
# print(np.std(chineses))
# print(np.std(englishs))
# print(np.std(maths))
# print(np.var(chineses))
# print(np.var(englishs))
# print(np.var(maths))

|科目|平均成绩|最小成绩|最大成绩|方差|标准差|
|语文|84.8|66|95|114.96000000000001|10.721940122944169|
|英语|84.0|65|92|95.6|9.777525249264253|
|数学|78.2|30|98|634.56|25.19047439013406|


In [45]:
# Series
import pandas as pd
from pandas import Series,DataFrame
x1 = Series([1,2,3,4])
x2 = Series(data=[1,2,3,4], index = ['a','b','c','d'])
print(f'x1:\n{x1},\n x2:\n{x2}')

x1:
0    1
1    2
2    3
3    4
dtype: int64,
 x2:
a    1
b    2
c    3
d    4
dtype: int64


In [46]:
## 字典方式创建
d = {'a':1,'b':2,'c':3,'d':4}
x3 = Series(d)
print(x3)

a    1
b    2
c    3
d    4
dtype: int64


In [47]:
# DataFrame
data = {'Chinese':[92,95,93,90,80],'English':[65,85,92,88,90],'Math':[86,98,96,77,90]}
df1 = DataFrame(data)
df2 = DataFrame(data,index=['zhangfei','Guanyu','Zhaoyun','Huangzhong','Dianwei'], columns=['English','Math','Chinese'])
print(df1)
print(df2)

   Chinese  English  Math
0       92       65    86
1       95       85    98
2       93       92    96
3       90       88    77
4       80       90    90
            English  Math  Chinese
zhangfei         65    86       92
Guanyu           85    98       95
Zhaoyun          92    96       93
Huangzhong       88    77       90
Dianwei          90    90       80


In [48]:

## 数据导入和输出
# score = DataFrame(pd.read_excel('data.xlsx'))
# score.to_excel('data1.xlsx')
# print(score)

# 数据清洗
## 删除DataFrame中不必要的行或列
# df2 = df2.drop(columns=['Chinese'])
# df2
# df2 = df2.drop(index=['zhangfei'])
# df2
## 重命名列名columns,让列表明更容易识别
# df2.rename(columns={'Chinese':'yuwen','English':'yingyu'},inplace=True)
# df2
## 去重复的值
# 格式问题
## 更改数据格式
df2['Chinese'].astype('str')

# df2['Chinese'].astype(np.int64)
## 删除空格
# df2['Chinese'] = df2['Chinese'].map(str.strip)
# df2['Chinese'] = df2['Chinese'].map(str.lstrip)
# df2['Chinese'] = df2['Chinese'].map(str.rstrip)
# ### 特殊字符
# df2['Chinese'] = df2['Chinese'].str.strip('$')
### 大小写转换
### 查找空值

zhangfei      92
Guanyu        95
Zhaoyun       93
Huangzhong    90
Dianwei       80
Name: Chinese, dtype: object

In [49]:
# 使用Apply函数对数据进行清洗
# df2['Chinese'] = df2['Chinese'].astype('str')
# df2['Chinese'] = df2['Chinese'].apply(str.upper)
# df2
# def double_df(x):
#     return 2*x
# df2['语文'] = df2['Chinese'].apply(double_df)
# df2

def plus(df,n,m):
    df['new1'] = (df['Chinese']+df['English']) * m
    df['new2'] = (df['English']+df['Chinese']) * n
    return df
df2 = df2.apply(plus,axis=1,args=(2,3))
df2

English  Math  Chinese  new1  new2
zhangfei         65    86       92   471   314
Guanyu           85    98       95   540   360
Zhaoyun          92    96       93   555   370
Huangzhong       88    77       90   534   356
Dianwei          90    90       80   510   340

In [50]:
# 数据统计
df1 = DataFrame({'name':['Zhangfei','GuanYu','a','b','c'],'data1':range(5)})
print(df1.describe())

          data1
count  5.000000
mean   2.000000
std    1.581139
min    0.000000
25%    1.000000
50%    2.000000
75%    3.000000
max    4.000000


In [51]:
# 数据表合并
df1 = DataFrame({'name':['ZhangFei', 'GuanYu', 'a', 'b', 'c'], 'data1':range(5)})
df2 = DataFrame({'name':['ZhangFei', 'GuanYu', 'A', 'B', 'C'], 'data2':range(5)})

In [52]:
# 基于指定列进行链接
df3 = pd.merge(df1,df2,on='name')
df3

name  data1  data2
0  ZhangFei      0      0
1    GuanYu      1      1

In [53]:
# inner内连接
df3 = pd.merge(df1,df2,how='inner')
df3

name  data1  data2
0  ZhangFei      0      0
1    GuanYu      1      1

In [54]:
# left左连接
df3 = pd.merge(df1,df2,how='left')
df3

name  data1  data2
0  ZhangFei      0    0.0
1    GuanYu      1    1.0
2         a      2    NaN
3         b      3    NaN
4         c      4    NaN

In [55]:
# right右连接
df3 = pd.merge(df1,df2,how='right')
df3

name  data1  data2
0  ZhangFei    0.0      0
1    GuanYu    1.0      1
2         A    NaN      2
3         B    NaN      3
4         C    NaN      4

In [60]:
# outer外连接
df3 = pd.merge(df1,df2,how='outer')
df3



name  data1  data2
0  ZhangFei    0.0    0.0
1    GuanYu    1.0    1.0
2         a    2.0    0.0
3         b    3.0    0.0
4         c    4.0    0.0
5         A    0.0    2.0
6         B    0.0    3.0
7         C    0.0    4.0

In [58]:
# 用SQL方式打开Pandas
import pandas as pd
from pandas import DataFrame
from pandasql import sqldf,load_meat,load_births
df1 = DataFrame({'name':['ZhangFei', 'GuanYu', 'a', 'b', 'c'], 'data1':range(5)})
pysqldf = lambda sql: sqldf(sql,globals())
sql = "select * from df1 where name = 'ZhangFei'"
print(pysqldf(sql))

       name  data1
0  ZhangFei      0


In [166]:
# 练习题
import pandas as pd
from pandas import Series, DataFrame

data1 = pd.DataFrame({'name':['Zhangfei','Guanyu','Zhaoyun','Huangzhong','Dianwei','Dianwei'],'Chinese':[66,95,95,90,80,80],'English':[65,85,92,88,90,90],'Math':[None,98,96,77,90,90]})
data1

# 去处重复行
df1 = data1.drop_duplicates()
# 替换缺失值
df1 = df1.fillna(0)
# 增加总和
def sum(df):
    df['sum']  = (df['Chinese']+df['English']+df['Math'])
    return df

df1 = df1.apply(sum,axis=1)
df1


name  Chinese  English  Math    sum
0    Zhangfei       66       65   0.0  131.0
1      Guanyu       95       85  98.0  278.0
2     Zhaoyun       95       92  96.0  283.0
3  Huangzhong       90       88  77.0  255.0
4     Dianwei       80       90  90.0  260.0