In [1]:
num = 0
for i in range(1, 1000, 2):
    num += i
print(num)

250000


In [2]:
num = sum(range(1, 1000, 2))
print(num)

250000


In [8]:
import numpy as np

a = np.array([1,2,3,4,5,6])
b = np.array([[1,2,3],[4,5,6],[7,8,9,]])

b[1,1] = 10

a.shape
b.shape
a.dtype
b


array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [27]:
# -*- coding: utf-8 -*-

import  numpy as np
import string

persontype = np.dtype({'names':['name','age','chinese','math', 'english'], 'formats':['S32', 'i', 'i', 'i', 'f']})
person = np.array([('zhangfei', 32, 67,46,82),('zhangfei', 32, 67,46,82),('zhangfei', 32, 67,46,82),('zhangfei', 32, 67,46,82)], dtype=persontype)

ages = person['age'][:]
ages
chineses = person['chinese'][:]
chineses
maths = person['math'][:]
maths
englishs = person[:]['english']
englishs

print('age mean:', np.mean(ages))
print('chinese mean:', np.mean(chineses))
print('math mean:', np.mean(maths))
print('english mean:', np.mean(englishs))



age mean: 32.0
chinese mean: 67.0
math mean: 46.0
english mean: 82.0


In [29]:
x1 = np.arange(1, 11, 2)
x2 = np.linspace(1, 9, 5)
print(x1)
print(x2)

[1 3 5 7 9]
[1. 3. 5. 7. 9.]


In [33]:
for i in range(1, 10):
    for j in range(1, i+1):
        print(r'{} X {} = {}'.format(j, i, i*j), end='\t')
    print()

1 X 1 = 1	
1 X 2 = 2	2 X 2 = 4	
1 X 3 = 3	2 X 3 = 6	3 X 3 = 9	
1 X 4 = 4	2 X 4 = 8	3 X 4 = 12	4 X 4 = 16	
1 X 5 = 5	2 X 5 = 10	3 X 5 = 15	4 X 5 = 20	5 X 5 = 25	
1 X 6 = 6	2 X 6 = 12	3 X 6 = 18	4 X 6 = 24	5 X 6 = 30	6 X 6 = 36	
1 X 7 = 7	2 X 7 = 14	3 X 7 = 21	4 X 7 = 28	5 X 7 = 35	6 X 7 = 42	7 X 7 = 49	
1 X 8 = 8	2 X 8 = 16	3 X 8 = 24	4 X 8 = 32	5 X 8 = 40	6 X 8 = 48	7 X 8 = 56	8 X 8 = 64	
1 X 9 = 9	2 X 9 = 18	3 X 9 = 27	4 X 9 = 36	5 X 9 = 45	6 X 9 = 54	7 X 9 = 63	8 X 9 = 72	9 X 9 = 81	


In [51]:
x1 = np.arange(1, 11, 2)
x2 = np.linspace(1, 9, 5)
x1, x2

(array([1, 3, 5, 7, 9]), array([1., 3., 5., 7., 9.]))

In [65]:
np.add(x1, x2)
np.subtract(x1, x2)
np.multiply(x1, x2)
np.divide(x1, x2)
np.power(x1, x2)
np.remainder(x1, x2)

array([0., 0., 0., 0., 0.])

In [59]:
score = {"guanyu":95, 'zhangfei': 96}
score['zhaoyun'] = 98
score

98


In [60]:
s = set(['a', 'b', 'c'])
s.add('d')
s

{'a', 'b', 'c', 'd'}

In [61]:
s.remove('b')
print('c' in s)

True


In [62]:
while True:
    try:
        line = raw_input()
        a = line.split()
        print(int(a[0]) + int(a[1]))
    except:
        break

In [71]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.amin(a)
np.amin(a, 0)
np.amin(a, 1)
np.amax(a)

9

In [74]:
np.ptp(a)
np.ptp(a, 0)
np.ptp(a, 1)

array([2, 2, 2])

In [81]:
np.percentile(a, 100)
np.percentile(a, 100, 0)
# np.percentile(a, 50, 1)

array([7., 8., 9.])

In [84]:
np.median(a)
np.median(a, 0)
np.median(a, 1)

array([2., 5., 8.])

In [86]:
a = np.array([1,2,3,4])
wts = np.array([1,2,3,4])
np.average(a)
np.average(a, weights=wts)

3.0

In [88]:
a = np.array([1,2,3,4])
np.std(a)
np.var(a)

1.25

In [108]:
num = 0
# for i in range(1, 100, 2):
#     num += i
# num
for i in np.linspace(1, 99, 50):
    num += i
num

2500.0

In [148]:
# -*- coding: utf-8 -*-  
persontype = np.dtype({'names':['姓名','语文','英语','数学'], 'formats':['S32','i','i','i']})

persons = np.array([('ZhangFei',66,65,30),('GuanYu',95,85,98),('ZhaoYun',93,92,96), ('HuangZhong',90,88,77),('DianWei', 80,90,90)], dtype=persontype)

In [183]:
chineses = persons[:]['语文']
englishs = persons[:]['英语']
maths  = persons[:]['数学']

print('Chinese mean:', np.mean(chineses))
print('Math mean:', np.mean(maths))
print('English mean:', np.mean(englishs))
print('*'*20, '\n')
print('Chinese min:', np.amin(chineses))
print('Math min:', np.amin(maths))
print('English min:', np.amin(englishs))
print('*'*20, '\n')
print('Chinese max:', np.amax(chineses))
print('Math max:', np.amax(maths))
print('English max:', np.amax(englishs))
print('*'*20, '\n')
print('Chinese std:', np.std(chineses))
print('Math std:', np.std(maths))
print('English std:', np.std(englishs))
print('*'*20, '\n')
print('Chinese var:', np.var(chineses))
print('Math var:', np.var(maths))
print('English var:', np.var(englishs))
print('*'*20, '\n')
print('*'*20, '\n')

def show(names, num):
    print(f'|{names}|{np.mean(num)}|{np.amin(num)}|{np.amax(num)}|{np.var(num)}|{np.std(num)}')


print('|科目|平均|最小|最大|方差|标准差|')
show('语文', chineses)
show('数学', maths)
show('英语', englishs)

Chinese mean: 84.8
Math mean: 78.2
English mean: 84.0
******************** 

Chinese min: 66
Math min: 30
English min: 65
******************** 

Chinese max: 95
Math max: 98
English max: 92
******************** 

Chinese std: 10.721940122944169
Math std: 25.19047439013406
English std: 9.777525249264253
******************** 

Chinese var: 114.96000000000001
Math var: 634.56
English var: 95.6
******************** 

******************** 

|科目|平均|最小|最大|方差|标准差|
|语文|84.8|66|95|114.96000000000001|10.721940122944169
|数学|78.2|30|98|634.56|25.19047439013406
|英语|84.0|65|92|95.6|9.777525249264253


In [186]:
print('排名')
ranking=sorted(persons, key=lambda x:x[1]+x[2]+x[3], reverse=True)
ranking

排名


[(b'ZhaoYun', 93, 92, 96),
 (b'GuanYu', 95, 85, 98),
 (b'DianWei', 80, 90, 90),
 (b'HuangZhong', 90, 88, 77),
 (b'ZhangFei', 66, 65, 30)]

In [187]:
import pandas as pd
from pandas import Series, DataFrame
x1 = Series([1,2,3,4])
x2 = Series(data=[1,2,3,4], index=['a','b','c','d'])
print(f'x1:\n{x1}, \n x2:\n{x2}')

x1:
0    1
1    2
2    3
3    4
dtype: int64, 
 x2:
a    1
b    2
c    3
d    4
dtype: int64


In [188]:
data={'chinese': [66,35,67,32,44],'math':[45,76,45,21,55],'english':[23,77,34,13,78]}
df1=DataFrame(data)
df2 = DataFrame(data, index=['zhangfei','Guanyu','zhaoyun','huangzhong','dianwei'])
print(df1)
print(df2)

   chinese  math  english
0       66    45       23
1       35    76       77
2       67    45       34
3       32    21       13
4       44    55       78
            chinese  math  english
zhangfei         66    45       23
Guanyu           35    76       77
zhaoyun          67    45       34
huangzhong       32    21       13
dianwei          44    55       78
