In [1]:
import numpy as np

In [2]:
a = np.array([[4,3,2], [2,4,1]])
a

array([[4, 3, 2],
       [2, 4, 1]])

In [3]:
np.sort(a)

array([[2, 3, 4],
       [1, 2, 4]])

In [4]:
np.sort(a, axis=None)

array([1, 2, 2, 3, 4, 4])

In [5]:
np.sort(a, axis=1)

array([[2, 3, 4],
       [1, 2, 4]])

In [7]:
np.sort(a, axis=0)

array([[2, 3, 1],
       [4, 4, 2]])

In [17]:
persontype=np.dtype({'names':['name','age','chinese','math', 'english'], 'formats':['S32', 'i','i','i','f']})
peoples = np.array([('张飞', 32,65,23,56.5), ('关羽',34,65,43,25),('赵云',27,67,98,97),('黄忠', 54,23,48,72),('典韦', 37, 38, 84, 73)])
peoples

array([['张飞', '32', '65', '23', '56.5'],
       ['关羽', '34', '65', '43', '25'],
       ['赵云', '27', '67', '98', '97'],
       ['黄忠', '54', '23', '48', '72'],
       ['典韦', '37', '38', '84', '73']], dtype='<U4')

In [9]:
persontype = np.dtype({'names':['name','age','chinese','math','english'],'formats':['S32','i','i','i','f']})
perples = np.array([('张飞',32,77,100,90),('关羽',24,85,96,88.5),('赵云',28,85,42,25.5)])
perples

array([['张飞', '32', '77', '100', '90'],
       ['关羽', '24', '85', '96', '88.5'],
       ['赵云', '28', '85', '42', '25.5']], dtype='<U4')

In [18]:
import feather
import numpy as np
import pandas as pd

np.random.seed=42
df_size = 10000000

df = pd.DataFrame({
    'a': np.random.rand(df_size),
    'b': np.random.rand(df_size),
    'c': np.random.rand(df_size),
    'd': np.random.rand(df_size),
    'e': np.random.rand(df_size)
})

df.sample(5)

a         b         c         d         e
2416532  0.408202  0.246426  0.669367  0.370027  0.783769
5329891  0.880863  0.898593  0.005983  0.526412  0.008446
8698511  0.900987  0.103887  0.179654  0.608061  0.809559
1603815  0.295465  0.329103  0.979261  0.194567  0.671258
9965363  0.832103  0.639692  0.366761  0.824298  0.154312

In [ ]:
df.to_feather('~/data/1M.feather')