In [9]:
# Numpy相关
import numpy as np
# Numpy中axis的使用
a = np.array([[4,3,2],[2,4,1]])
print(a)
print("*"*30)
print(np.sort(a))
print("*"*30)
print(np.sort(a,axis=None))
print("*"*30)
print(np.sort(a,axis=0))
print("*"*30)
print(np.sort(a, axis=1))

[[4 3 2]
 [2 4 1]]
******************************
[[2 3 4]
 [1 2 4]]
******************************
[1 2 2 3 4 4]
******************************
[[2 3 1]
 [4 4 2]]
******************************
[[2 3 4]
 [1 2 4]]


In [12]:
# 答疑 2：定义结构数组中的 S32 代表什么意思？
persontype = np.dtype({'names':['name','age','chinese','math','english'],'formats':['S32','i','i','i','f']})
perples = np.array([('张飞',32,77,100,90),('关羽',24,85,96,88.5),('赵云',28,85,42,25.5)])
perples

array([['张飞', '32', '77', '100', '90'],
       ['关羽', '24', '85', '96', '88.5'],
       ['赵云', '28', '85', '42', '25.5']], dtype='<U4')

In [15]:
# 为什么打印出来的 name 会带一个 b？

student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student)
print(a)
print(a['name'])

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
[b'abc' b'xyz']


In [16]:
# np.ceil是什么意思
# 向上取整
np.ceil(2.4)

3.0

In [20]:
# 作业1
a = np.array([[4,3,2],[2,4,1]])
print(np.sort(a,axis=0))

[[2 3 1]
 [4 4 2]]
