In [24]:
import pandas as pd
from sklearn import preprocessing
from sklearn.cluster import KMeans

# 输入数据
data = pd.read_excel('data/asia_football_club.xlsx',encoding='gbk')
print(data)
tx = data[['2019年国际排名','2018世界杯','2015亚洲杯']]
df = pd.DataFrame(tx)

# 将数据进行规范化
mms = preprocessing.MinMaxScaler()
tx = mms.fit_transform(tx)

#kmeans算法
kmeans = KMeans(n_clusters=3)
kmeans.fit(tx)
predict_y = kmeans.predict(tx)
print(predict_y)

# 合并聚类结果，插入到元数据中
result = pd.concat((data, pd.DataFrame(predict_y)), axis=1)
result.rename({0:u'聚类'},axis=1,inplace=True)
result


        国家  2019年国际排名  2018世界杯  2015亚洲杯
0       中国         73       40        7
1       日本         60       15        5
2       韩国         61       19        2
3       伊朗         34       18        6
4       沙特         67       26       10
5      伊拉克         91       40        4
6      卡塔尔        101       40       13
7      阿联首         81       40        6
8   乌兹别克斯坦         88       40        8
9       泰国        122       40       17
10      越南        102       50       17
11      阿旻         87       50       12
12      巴林        116       50       11
13      朝鲜        110       50       14
14      印尼        164       50       17
15      澳洲         40       30        1
16     叙利亚         76       40       17
17      约旦        118       50        9
18     科威特        160       50       15
19    巴勒斯坦         96       50       16
[2 0 0 0 0 2 1 2 2 1 1 1 1 1 1 0 1 1 1 1]


国家  2019年国际排名  2018世界杯  2015亚洲杯  聚类
0       中国         73       40        7   2
1       日本         60       15        5   0
2       韩国         61       19        2   0
3       伊朗         34       18        6   0
4       沙特         67       26       10   0
5      伊拉克         91       40        4   2
6      卡塔尔        101       40       13   1
7      阿联首         81       40        6   2
8   乌兹别克斯坦         88       40        8   2
9       泰国        122       40       17   1
10      越南        102       50       17   1
11      阿旻         87       50       12   1
12      巴林        116       50       11   1
13      朝鲜        110       50       14   1
14      印尼        164       50       17   1
15      澳洲         40       30        1   0
16     叙利亚         76       40       17   1
17      约旦        118       50        9   1
18     科威特        160       50       15   1
19    巴勒斯坦         96       50       16   1

In [ ]:
# 划分成5类
import pandas as pd
from sklearn import preprocessing
from sklearn.cluster import KMeans

# 输入数据
data = pd.read_excel('data/asia_football_club.xlsx',encoding='gbk')
print(data)
tx = data[['2019年国际排名','2018世界杯','2015亚洲杯']]
df = pd.DataFrame(tx)

# 将数据进行规范化
mms = preprocessing.MinMaxScaler()
tsx = mms.fit_transform(tx)

#kmeans算法
kmeans = KMeans(n_clusters=5)
kmeans.fit(tsx)
predict_y = kmeans.predict(tsx)
print(predict_y)

# 合并聚类结果，插入到元数据中
result = pd.concat((data, pd.DataFrame(predict_y)), axis=1)
result.rename({0:u'聚类'},axis=1,inplace=True)
result

In [109]:
# 图像分割
import pandas as pd
from pandas import Series,DataFrame
import numpy as np
import PIL.Image as image
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from skimage import color

# 加载图像，对数据进行规范化
def load_data(filePath):
    # 读取文件
    f = open(filePath, 'rb') # 二进制读取
    data = []
    # 得到图像的像素值
    img = image.open(f)
    # 得到图像尺寸
    width, height = img.size
    for x in range(width):
        for y in range(height):
            # 得到点x,y的三个通道值
            c1,c2,c3 = img.getpixel((x,y))
            data.append([c1,c2,c3])
    f.close()
    # 采用Min-Max规范化
    mm = MinMaxScaler()
    data = mm.fit_transform(data)
    return np.mat(data), width, height

# 加载图像，得到规范化的结果img, 以及图像尺寸
img, width, height = load_data('data/weixin.jpg')
img = pd.DataFrame(img,columns=['R','G','B'])
print(f'img:\n {img}')


# 用K-Means对图像进行16聚类
kmeans = KMeans(n_clusters = 2)
label = kmeans.fit_predict(img)
# pred = pd.DataFrame(label, columns=['pred']).to_csv('pred_2.csv')

# 将图像聚类结果，转化成图像尺寸的矩阵
label = label.reshape([width, height])

# 创建个新图像pic_mark,用于保存图像聚类的结果，并设置不同的灰度值
pic_mark = image.new('L',(width, height))

for x in range(width):
    for y in range(height):
        # 根据类别设置图像灰度，类别0 灰度值为255， 类别1 灰度值为127
        pic_mark.putpixel((x,y), int(256/(label[x][y]+1))-1)

pic_mark.save('weixin_mark.jpg', 'JPEG')

img:
                 R         G         B
0        0.004202  0.004065  0.003922
1        0.004202  0.004065  0.003922
2        0.004202  0.004065  0.003922
3        0.004202  0.004065  0.003922
4        0.004202  0.004065  0.003922
...           ...       ...       ...
1032505  0.012605  0.036585  0.090196
1032506  0.012605  0.036585  0.090196
1032507  0.012605  0.036585  0.090196
1032508  0.012605  0.036585  0.090196
1032509  0.012605  0.036585  0.090196

[1032510 rows x 3 columns]


In [93]:
# 图像分割(color)
import pandas as pd
from pandas import Series,DataFrame
import numpy as np
import PIL.Image as image
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from skimage import color

# 加载图像，对数据进行规范化
def load_data(filePath):
    # 读取文件
    f = open(filePath, 'rb') # 二进制读取
    data = []
    # 得到图像的像素值
    img = image.open(f)
    # 得到图像尺寸
    width, height = img.size
    for x in range(width):
        for y in range(height):
            # 得到点x,y的三个通道值
            c1,c2,c3 = img.getpixel((x,y))
            data.append([c1,c2,c3])
    f.close()
    # 采用Min-Max规范化
    mm = MinMaxScaler()
    data = mm.fit_transform(data)
    return np.mat(data), width, height

# 加载图像，得到规范化的结果img, 以及图像尺寸
img, width, height = load_data('data/weixin.jpg')


# 用K-Means对图像进行16聚类
kmeans = KMeans(n_clusters = 16)
label = kmeans.fit_predict(img)
# pred = pd.DataFrame(label, columns=['pred']).to_csv('pred_16.csv')


# 将图像聚类结果，转化成图像尺寸的矩阵
label = label.reshape([width, height])

# 将聚类标识矩阵转化为不同颜色的矩阵
label_color = (color.label2rgb(label)*255).astype(np.uint8)
label_color = label_color.transpose(1,0,2)
images = image.fromarray(label_color)
images.save('weixin_color.jpg','JPEG')

In [83]:
# 0-255数值投射 rgb

# 图像分割
import pandas as pd
from pandas import Series,DataFrame
import numpy as np
import PIL.Image as image
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from skimage import color

# 加载图像，对数据进行规范化
def load_data(filePath):
    # 读取文件
    f = open(filePath, 'rb') # 二进制读取
    data = []
    # 得到图像的像素值
    img = image.open(f)
    # 得到图像尺寸
    width, height = img.size
    for x in range(width):
        for y in range(height):
            # 得到点x,y的三个通道值
            c1,c2,c3 = img.getpixel((x,y))
            data.append([(c1+1)/256.0,(c2+1)/256.0,(c3+1)/256.0])
    f.close()
#     # 采用Min-Max规范化
#     mm = MinMaxScaler()
#     data = mm.fit_transform(data)
    return np.mat(data), width, height

# 加载图像，得到规范化的结果img, 以及图像尺寸
img, width, height = load_data('data/weixin.jpg')
print(f'img:\n{img}')

# 用K-Means对图像进行16聚类
kmeans = KMeans(n_clusters = 16)
label = kmeans.fit_predict(img)

# 将图像聚类结果，转化成图像尺寸的矩阵
label = label.reshape([width, height])
# 创建一个新图像img, 用来保存图像聚类压缩后的结果
img = image.new('RGB', (width, height))
for x in range(width):
    for y in range(height):
        c1 = kmeans.cluster_centers_[label[x,y],0]
        c2 = kmeans.cluster_centers_[label[x,y],1]
        c3 = kmeans.cluster_centers_[label[x,y],2]
        img.putpixel((x,y),(int(c1*256)-1,int(c2*256)-1,int(c3*256)-1))
img.save('weixin_rgb.jpg', 'JPEG')

width:762, height:1355,
img:
 [[0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]
 ...
 [0.015625  0.0390625 0.09375  ]
 [0.015625  0.0390625 0.09375  ]
 [0.015625  0.0390625 0.09375  ]]
label:[7 7 7 ... 1 1 1]


In [111]:
# 课后作业
import pandas as pd
import numpy as np
import PIL.Image as image
from pandas import Series,DataFrame
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from skimage import color

def load_data(filePath):
    # 读取文件
    f = open(filePath, 'rb')
    data = []
    # 得到图像的像素值
    img = image.open(f)
    # 得到图像尺寸
    width, height = img.size
    for x in range(width):
        for y in range(height):
            # 得到点x,y的三个通道值
            c1,c2,c3 = img.getpixel((x,y))
            data.append([c1,c2,c3])
    f.close()
    # 采用Min-Max规范化
    mm = MinMaxScaler()
    data = mm.fit_transform(data)
    return np.mat(data), width,  height

# 加载图像，得到规范化的结果img, 以及图像尺寸
img, width, height = load_data('data/son.jpeg')

# 用K-Means对图像进行16聚类
kmeans = KMeans(n_clusters = 16)
label = kmeans.fit_predict(img)

# 将图像聚类结果，转化成图像尺寸的矩阵
label = label.reshape([width, height])
# 创建一个新图像img, 用来保存图像聚类压缩后的结果
img = image.new('RGB', (width, height))
for x in range(width):
    for y in range(height):
        img.putpixel((x,y),int(256/(label[x][y]+1))-1)

# 将聚类表示矩阵幻化成不同颜色的矩阵
label_color = (color.label2rgb(label)*255).astype(np.uint8)
label_color = label_color.transpose(1,0,2)
images = image.fromarray(label_color)
images.save('data/son_color.jpg','JPEG')


